esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

time:
  - platform: homeassistant
    id: homeassistant_time

# Disable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret ha_password

ota:
  password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: ${fancyname} RSSI
    update_interval: 60s

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current:
      name: ${fancyname} Current
      accuracy_decimals: 3
      icon: mdi:mdi-flash-auto
      unit_of_measurement: A
    voltage:
      name: ${fancyname} Voltage
      accuracy_decimals: 1
      unit_of_measurement: V
      icon: mdi:current-ac
    power:
      id: wattage
      name: ${fancyname} Power
      accuracy_decimals: 0
      unit_of_measurement: W
      icon: mdi:hydro-power
    update_interval: 3s
    change_mode_every: 8
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}

  - platform: total_daily_energy
    name: ${fancyname} Total Daily Energy
    icon: mdi:circle-slice-3
    power_id: wattage
    min_save_interval: 6h
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    accuracy_decimals: 3

binary_sensor:
  - platform: gpio
    device_class: power
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
      inverted: True
    name: ${fancyname} Button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: ${fancyname}
    pin: GPIO14
    id: relay
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on: # Action when relay is turned on
      - script.execute: led_power_on
    on_turn_off: # Action when relay is turned off
      - script.execute: led_relay_off

status_led:
  pin:
    number: GPIO01
    inverted: True

output:
- platform: esp8266_pwm
  id: ${devicename}_red_output
  pin:
    number: GPIO13
    inverted: True

light:
- platform: monochromatic
  name: ${fancyname} Light
  output: ${devicename}_red_output
  id: ${devicename}_red_led

interval:
  - interval: 2000ms
    then:
      - if:
          condition:
            for:
              time: 30s
              condition:
                not:
                  wifi.connected:
          then:
            - light.turn_on:
                id: ${devicename}_red_led
                brightness: 100%

script:
  - id: led_relay_off
    then:
      - light.turn_off:
          id: ${devicename}_red_led
  - id: led_power_on
    then:
      - light.turn_on:
          id: ${devicename}_red_led

